services:
  - type: web
    name: safeguard-ai-backend
    runtime: python
    runtimeVersion: 3.12.5
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: PYTHONPATH
        value: ./
